### ISSUE TITLE
跳转页面将token作为url参数会暴露token

### ISSUE THREAD

**Issue by nodejh** [nodejh/urp_scu#1]
问题：

+ 跳转页面将token作为url参数会暴露token，用户只要知道链接就能通过该系统获取教务系统信息
+ 登录教务系统后，token是唯一的。再次登录会重新获得一个token。

解决办法：

+ 只将token作为cookie参数，页面跳转的时候，获取cookie？

**Comment by nodejh** [comment]
在 http response 中设置 cookie。

[http://www.expressjs.com.cn/4x/api.html#res.cookie](http://www.expressjs.com.cn/4x/api.html#res.cookie)

**Comment by timehelun** [comment]
​
A页面：

let token = '123'
window.open('http://www.bbb.com', token)

B页面：

//console.log(window.name)
//123

let token = window.name


​
